import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { bytesToHex, hexToBytes } from './bytes.js';
import {
  createDeviceIdentityFromSeed,
  generateDeviceIdentity,
  signDeviceMessage,
  validateDeviceId,
  verifyDeviceSignature,
} from './identity.js';

interface TestVector {
  name: string;
  seed_hex: string;
  pub_key_hex: string;
  priv_key_hex: string;
  device_id: string;
  fingerprint: string;
  message_hex: string;
  sig_hex: string;
}

describe('identity & device fingerprint', () => {
  it('generates a valid device identity', async () => {
    const id = await generateDeviceIdentity();
    expect(id.publicKey.length).toBe(32);
    expect(id.privateKey.length).toBe(32);
    expect(validateDeviceId(id.deviceId)).toBe(true);
    expect(id.fingerprint.startsWith('SB1-')).toBe(true);

    const msg = new TextEncoder().encode('sendbeam-ts-identity-test');
    const sig = signDeviceMessage(id, msg);
    expect(sig.length).toBe(64);

    expect(verifyDeviceSignature(id.publicKey, msg, sig)).toBe(true);
    expect(verifyDeviceSignature(id.publicKey, new TextEncoder().encode('other'), sig)).toBe(false);

    const corruptedSig = new Uint8Array(sig);
    corruptedSig[0]! ^= 0xff;
    expect(verifyDeviceSignature(id.publicKey, msg, corruptedSig)).toBe(false);
  });

  it('matches all cross-language test vectors generated by Go wire package', async () => {
    const vectorPath = resolve(__dirname, '../../wire/testdata/identity-vectors.json');
    const rawData = readFileSync(vectorPath, 'utf8');
    const vectors: TestVector[] = JSON.parse(rawData);

    expect(vectors.length).toBeGreaterThanOrEqual(3);

    for (const v of vectors) {
      const seed = hexToBytes(v.seed_hex);
      const identity = await createDeviceIdentityFromSeed(seed);

      expect(bytesToHex(identity.publicKey)).toBe(v.pub_key_hex);
      expect(identity.deviceId).toBe(v.device_id);
      expect(identity.fingerprint).toBe(v.fingerprint);

      const msg = hexToBytes(v.message_hex);
      const sig = signDeviceMessage(identity, msg);
      expect(bytesToHex(sig)).toBe(v.sig_hex);

      expect(verifyDeviceSignature(identity.publicKey, msg, hexToBytes(v.sig_hex))).toBe(true);
    }
  });

  it('validates device ID format correctly', () => {
    expect(
      validateDeviceId('sb-dev-65b60673d6ed884bf01c2c222d82ada0740f29ac3355d6a925c81f17f47a27b8'),
    ).toBe(true);
    expect(
      validateDeviceId(
        'invalid-prefix-65b60673d6ed884bf01c2c222d82ada0740f29ac3355d6a925c81f17f47a27b8',
      ),
    ).toBe(false);
    expect(validateDeviceId('sb-dev-short')).toBe(false);
    expect(
      validateDeviceId('sb-dev-zzzz0673d6ed884bf01c2c222d82ada0740f29ac3355d6a925c81f17f47a27b8'),
    ).toBe(false);
  });
});
